name: Release Dev Stage

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      API_KEY: ${{ secrets.NEON_API_KEY }}
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0 
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.11"
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install neonctl and tsx
      run: npm install -g neonctl tsx
    - name: Delete Previous Branch
      run: neonctl branches delete dev --api-key ${{ env.API_KEY }}
      continue-on-error: true
    - name: Create Branched Database 
      run: neonctl branches create --name dev --api-key ${{ env.API_KEY }}
    - name: Branch Connection String in Parameter Store
      run: |
        export DB_URL=$(neonctl connection-string --branch dev --api-key ${{ env.API_KEY }})
        npx tsx src/cli/putSecret.js dev $DB_URL